import ICON from '../assets/icon.png';
import GOOGLE from '../assets/icons/google.png';
import GITHUB from '../assets/icons/github.png';
import CrossPlatforms from '../assets/images/crossplatforms.png';
import SpiderWebDark from '../assets/images/spider_web_d.png';
import SpiderWebLight from '../assets/images/spider_web_l.png';
import TierBronze from '../assets/icons/tier_bronze.png';
import TierChallenger from '../assets/icons/tier_challenger.png';
import TierDiamond from '../assets/icons/tier_diamond.png';
import TierGold from '../assets/icons/tier_gold.png';
import TierIron from '../assets/icons/tier_iron.png';
import TierMaster from '../assets/icons/tier_master.png';
import TierPlatinum from '../assets/icons/tier_platinum.png';
import TierSilver from '../assets/icons/tier_silver.png';

export const IC_ICON = ICON;
export const IC_GOOGLE = GOOGLE;
export const IC_GITHUB = GITHUB;
export const IC_TIER_BRONZE = TierBronze;
export const IC_TIER_CHALLENGER = TierChallenger;
export const IC_TIER_DIAMOND = TierDiamond;
export const IC_TIER_GOLD = TierGold;
export const IC_TIER_IRON = TierIron;
export const IC_TIER_MASTER = TierMaster;
export const IC_TIER_PLATINUM = TierPlatinum;
export const IC_TIER_SILVER = TierSilver;

export const IMG_CROSSPLATFORMS = CrossPlatforms;
export const IMG_SPIDER_WEB_DARK = SpiderWebDark;
export const IMG_SPIDER_WEB_LIGHT = SpiderWebLight;
